### ISSUE TITLE
Schema error when running from command line

### ISSUE THREAD

**Issue by glendaviesnz** [creditkarma/graphql-validator#1]
Hi

Firstly - thanks for releasing this useful tool :-)

I have managed to get the tool running via a .js file and node, eg. 

loader.loadSchema('./src/schema/*.graphql', (err, schema) => {
  validator.validateQueryFiles('./src/queries/*.graphql', schema, (err, results) => {
    console.log(results)
  })
})

and that is returning either an empty array, or an array of errors as expected ... but if I run from the command line I get 

Errors found:

But no output. If I debug this, it is because rather than array of file errors I get 

"Error: Schema must be an instance of GraphQLSchema. Also ensure that there are not multiple versions of GraphQL installed in your node_modules directory."

if I dump the schema that is passed into validateQueries() it appears to be a valid schema (and the same schema that is validating ok via node script), and I only have one version of graphql in node_modules directory that I can tell.

Any ideas on what to check? I am running on Windows. Basic schema and query that I am using for testing below. No major panic on this as we are just in an exploratory phase at the moment and can use a  node script rather than command line for our initial testing.

Thanks
Glen

schema.graphql
*****************
type Author {
  id: Int! 
  firstName: String
  lastName: String
  posts: [Post] 
}

type Post {
  id: Int!
  title: String
  author: Author
  votes: Int
}
type Query {
  posts: [Post]
}
type Mutation {
  upvotePost (
    postId: Int!
  ): Post
}
schema {
  query: Query
  mutation: Mutation
}

query.graphql
***************
  query Posts {
      posts {
          id,
          title,
          author {
              firstName,
              lastName
         }
      }
  }

**Comment by nnance** [comment]
@glendaviesnz sorry for the slow response I will look into this in the next couple of days.  are you still having the problem?

**Comment by nnance** [comment]
@glendaviesnz during the review of your issue I did find a couple of bugs.  not sure if it was released but I have released a new version and confirmed it works from the cli with your examples above.  Please confirm so I can close this issue.

**Comment by glendaviesnz** [comment]
Thanks. Using the latest release I no longer get the ""Error: Schema must be an instance of GraphQLSchema" error, but instead get "All queries are valid" from command line. 

However, I get this even if there are invalid queries?

If you have a look at https://github.com/glendaviesnz/graphql-validator-test - if I run the index.js script I get the correct "GraphQLError: Cannot query field "firstName" on type "Author". Did you mean "XfirstName" or "lastName"?" error. 

But if I run  graphql-validator -s "./test/schema/schema.graphql" "./test/queries/queries.graphql" from command line I get "All queries are valid".

The only difference I can spot is that when running from index.js it is using the locally installed 
  "@creditkarma/graphql-loader": "^0.2.0",
   "@creditkarma/graphql-validator": "^0.1.6"

But when using the global package from command line the fresh install of graphql-validator: 0.1.6 has a dependency of graphql-loader: 0.1.9 instead of 0.2.0 - not sure if that makes any difference. 

No panic at all to get back to me in this.

Thanks
Glen

**Comment by nnance** [comment]
Thanks for continue to work on this with me.  I had also noticed that bad queries didn't print errors just after I sent you the last message.  As I continued to work on the problem I released the loader while I was still working on the validator.  Both have now been updated to 0.2.0.  I bumped it to a new minor version because now you have to globally install graphql along with the validator for everything to work properly.  Clearly we need to add test coverage for the cli of validator.

Check it out let me know

**Comment by glendaviesnz** [comment]
ok - some success, thanks. The cli validator now returns error messages as expected after updating -g installs to 0.2.0

However, now the usage of the local installs of 0.2.0 versions in .js file return undefined for results parameter  for both error and no error returns. Have pushed the updated version to the repo mentioned above - but will try and do a bit more debugging on it tomorrow.

Thanks.

**Comment by glendaviesnz** [comment]
It was just the change in validateQueryFiles from 
callback ? callback(null, errors) : resolve(errors)
to
callback ? callback(errors) : reject(errors)

that caused the issue, as I was still expecting two params in the callback.

I am assuming that when using the tool this way to assume that if value returned in the callback passed into validateQueryFiles is undefined then just assume that everything passed? I have put a pull request in for a minor change to README to clarify this if this is the case. 

Thanks
Glen

**Comment by nnance** [comment]
Yes, that is the significance of the change to fix the cli tool.  The api when used with promises wasn't clear.  The cli tool expected .catch to be called if the validation failed.  So I figured the callback should return the errors in the error parameter.  Thanks for the README PR!

Do you think we are good to close this now?

**Comment by glendaviesnz** [comment]
Thanks for all the follow up - all sorted from our end now.
